### ISSUE TITLE
unable import storageninja.database.schema.hds_cs

### ISSUE THREAD

**Issue by ghost** [spurin/HDS-Storage-Compliance-Tool#2]
Traceback (most recent call last):
  File "hds_storage_compliance_tool.py", line 35, in <module>
    import storageninja.database.schema.hds_cs
  File "/home/test/hds/storageninja/database/schema/hds_cs.py", line 21
##     return {c.name: getattr(self, c.name) for c in self.**table**.columns}   "

unable to import under rhel 6.5 64bit os

**Comment by spurin** [comment]
Hey pbra,

What version of python are you using ?

**Comment by ghost** [comment]
hi James, its python 2.7, will try it on upper 3.version and will get you in few days, thank you

**Comment by spurin** [comment]
Cool, referring to your other comment, you will need to update the config file also to reflect your HiCommand server

**Comment by ghost** [comment]
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.


C:\HDS_TOOLS_hds_py_audit>python hds_storage_compliance_tool.py
Traceback (most recent call last):
  File "hds_storage_compliance_tool.py", line 22, in <module>
    from storageninja.utilities.custom_logging import setup_logging
ImportError: cannot import name 'setup_logging'

now i am on python 3.5.1 and updated config and getting this above
-- hicommand_binary: /Users/test/Desktop/DVMCli_linux/HiCommandCLI
this setting taking this automatically under windows path like C:\Users\ .. ?.

**Comment by ghost** [comment]
hi, did all from scratch now its running like a charm
